if (!window.MM)
	MM={};
MM.Res={
	"Admin": "Администратор",
	"AdminSite": "Админка",
	"ArticleNotFound": "Статья с таким идендитификатором не найдена.",
	"Articles": "Статьи",
	"ArticlesTab": "Почитать",
	"BackToList": "Вернуться к списку",
	"Choose": "Выберите...",
	"Close": "Закрыть",
	"Comment": "Комментарий",
	"ConfirmPasswordErrorMessage": "Пароли не совпадают",
	"ConfirmPasswordLbl": "Подтвердите пароль",
	"CongratulationMsgTemplate": "Поздравляем {0}, Вы зарегистрировались на сайте MetalMastery. &lt;p/&gt; Для того чтобы попасть на сайт, кликните -&gt; http:\\fake.url ",
	"CongratulationSbjTemplate": "Регистрация MetalMastery",
	"Create": "Создать",
	"CreateDate": "Дата создания",
	"CreateNew": "Создать новое",
	"DefaultOption": "Выберите...",
	"Delete": "Удалить",
	"DeleteConfirmQuestion": "Вы действительно хотите удалить это?",
	"Description": "Описание",
	"Details": "Детали",
	"DublicateUser": "Пользователь с таким мылом уже существует!",
	"Edit": "Редактировать",
	"Email": "E-mail",
	"EmailIncorrect": "Не верно введено мыло",
	"EmailLbl": "Мыло",
	"EmailLength": "Длина e-mail адреса превышает 256 символов",
	"EnterBtn": "Вперёд",
	"EntranceTab": "Вход",
	"Exit": "Выход",
	"FieldLength": "Поле {0} не должно превышать {1} символов",
	"FieldRangeRestrict": "Значение поля {0} не должно быть меньше {1} и превышать {2}",
	"Format": "Формат",
	"FormatNotFound": "Формат с таким идендитификатором не найден.",
	"Formats": "Форматы",
	"IdEmptyError": "Идендитификатор не может быть пустым.",
	"LoginPasswordInvalid": "Пользователя с такими логином и паролем не существует, или Вы допустили ошибку!",
	"Material": "Материал",
	"MaterialNotFound": "Материал с таким идендитификатором не найден.",
	"Materials": "Материалы",
	"MetalMasteryTitle": "MetalMastery",
	"Name": "Название",
	"Owner": "Владелец",
	"PasswordIncorrect": "Пароль должен содержать латинские символы и цифры, а также хотя бы один символ из ! @ # $% ^ &amp;amp; + =",
	"PasswordLbl": "Пароль",
	"PasswordLength": "Длина пароля не должна быть менее 5 символов и превышать 32 символа",
	"Published": "Опубликован",
	"Rating": "Оценка",
	"RegistrationComplete": "Поздравляем, Вы зарегистрировались!",
	"RememberMeLbl": "Запомнить меня",
	"Role": "Роль",
	"RoleNotFound": "Ошибка во время создания пользователья, роль не найдена.",
	"Save": "Сохранить",
	"SignUpBtn": "Зарегаться",
	"State": "Состояние",
	"StateNotFound": "Статус с таким идендитификатором не найден.",
	"TagNotFound": "Тег с таким идендитификатором не найден.",
	"Tags": "Теги",
	"Text": "Текст",
	"ThingNotFound": "Штука с таким идендитификатором не найдена.",
	"Things": "Шняги",
	"ThingsTab": "Поглядеть",
	"Title": "Заголовок",
	"UnhandledException": "Возникла необработанная ошибка",
	"UrlIncorrect": "Не верно введен урл",
	"UserNotFound": "Пользователь с таким идендитификатором не найден.",
	"Users": "Пользователи",
	"WantToReg": "Хочешь зарегаться?",
	"Welcome": "Добро пожаловать {0}",
	"WelcomePrefix": "Привет",
	get: function(param) {
		return this[param] || param;
	}
};
